### ISSUE TITLE
IdleX looks blurred at high resolutions

### ISSUE THREAD

**Issue by SvbZ3r0** [serwy/idlex#16]
Self explanatory title.

IdleX vs Idle
![image](https://user-images.githubusercontent.com/57280279/99867278-09285580-2b6d-11eb-90a8-d15616f8fa65.png)

**Comment by penguinWeeb** [comment]
Change python's DPI settings.

**Comment by SvbZ3r0** [comment]
Wait what? How do I do that?

**Comment by SvbZ3r0** [comment]
![idlex compatibility](https://user-images.githubusercontent.com/57280279/166868543-239e6746-92de-46e2-8332-3d6ef820f57d.png)
![idlex compatibility 2](https://user-images.githubusercontent.com/57280279/166868553-972f6c5a-701f-41aa-b4ea-698eb4091fee.png)
Here's how to change DPI settings for a program in Windows.

Fixed the problem
